### PR TITLE
Closes issue #3 - Add Optional Identifiers to the Explicit Versioning specification schema.

### LINKED ISSUE #3: Optional Identifiers
After the Explicit Version schema we may want to use optional identifiers, like:

* 1.0.0.0-Alpha1
* 1.0.0.0-Beta1
* 1.0.0.0-RC1
* 1.0.0.0-Build123

And any other one we may need for our internal or public Software Release process.

This optional identifiers MUST NOT clash with the Explicit Versioning Specification Schema intentions:

For example not using an Optional Identifier to say that:

* Major Relase.
* Breaking change release.
* Compatible Release.
*  Fix Release.

A section in the Specification must be added to clarify this Optional Identifiers usage.

This is related with the Pull Request comment https://github.com/exadra37-versioning/explicit-versioning/pull/2#issuecomment-298021968

### PR DESCRIPTION
**Pull request by Exadra37**
Closes #3.

### CODE REVIEW

**Comment by Exadra37** [comment]
@sapioit 
@colomet
@bmitch

Please can you guys proof read it?

**Comment by colomet** [comment]
I´m still with the names. RELEASE maybe is not the best option. As we could have a release any time.

**Comment by colomet** [comment]
the optional indentifier can be called MODIFIER

**Comment by Exadra37** [comment]
@colomet 

The intention of the `Optional_Identifier` is not to act as a Modifier, that would defeat the Specification Schema.

Optional Identifier is a place to add additional info as per documentation, where at any moment we place something on it that modifies what the required identifiers are telling.

**Comment by colomet** [comment]
http://calver.org/#scheme

**Comment by Exadra37** [comment]
@colomet 

Modify identifier makes complete sense in the CalVer specification but is totally out of scope for Explicit Versioning specification definition, because they are another Software Versioning Specification with complete different goals from Explicit Versioning.

**Comment by sapioit** [comment]
I think the optional identifiers shall be used only for incomplete builds, like trying to push a patch only to have that code available for both review and usage on another PCs, but shall not be a public release, just an internal one, thus it could use something like a code for each person in the team followed by the number of the push that person sent for that specific version (i.e. `1.6.3.5-Sapioit-32`).

**Comment by Exadra37** [comment]
@sapioit 

A good example where Optional Identifiers are used a lot, is to create Alpha, Beta and Releases Candidates, before we create the Production Release with the same tag number.

Using it for personal identifiers is not a good use case in my opinion, for that you have Branches.

But as the the Identifier name says is an Optional one and here the best is to leave some liberty for each Developer to use it for their specific needs in the Software Release process.

**Comment by sapioit** [comment]
We could list both of those as examples of the usage of Optional Identifiers.

**Comment by Exadra37** [comment]
@sapioti

They are already in this Pull Request... check [here](https://github.com/exadra37-versioning/explicit-versioning/blob/961862a647ab70145ba14f495d49197a63083bf0/README.md#targeting-2000-production-release).

**Pull request merged**
